# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZHhq6ts5Cg1GShBMMKK86LYIMZxTXH2
"""

_={1.0: 'pp', 2: 'dd', 3:'ll'}
print(a.get(4, 'not found'))
print(dict.keys)

print(a)
print(a.update({4: 'tt'}))
print(a)
print(type(a))